# Generated by Django 4.0.4 on 2022-04-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
